#!/bin/bash # Script to change the directory to the user's home directory without using shell variables # Change to the home directory using the tilde (~) notation
cd ~ # Display the current working directory to confirm the change pwd
